language: python
python:
- "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
install:
  - pip install -r requirements.txt
script: pytest --cov=./tests/test.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: "__token__"
  skip_existing: true
  edge: true
  on:
    branch: main
