language: python
python:
- "3.6"
deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_PASSWORD
  distribution: "sdist bdist_wheel"
  skip_existing: true
  edge: true
  on:
    branch: main
