language: python
python:
  - "3.8"
services:
  - docker
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
    #  - docker build -t emcunderground/powerprotect:latest .
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=powerprotect tests/*.py
  - docker push emcunderground/powerprotect
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: "__token__"
  skip_existing: true
  edge: true
  on:
    branch: main
