language: python
python:
- "3.8"
- "3.6"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: coverage run tests/test.py
after_success:
  - codecov
deploy:
  provider: pypi
  username: "__token__"
  skip_existing: true
  edge: true
  on:
    branch: main
